[package]
name = "concurrency"
version = "0.1.0"
edition = "2024"

[dependencies]
threads = { path = "../threads" }
message-passing = { path = "../message-passing" }
shared-state = { path = "../shared-state" }